### ISSUE TITLE
FATHMM Installation

### ISSUE THREAD

**Issue by mkinnaman** [johannesreiter/LiFD#2]
Hi Johannes,

In the instructions for FATHMM it states to

"Check the line COMMAND = 'python3 fathmm.py -w Cancer {} {}' in lifd/databases/fathmm.py and correct the line to reflect the version of Python. Note that a separate installation of Python 2 will be necessary to run fathmm.py if the above corrections are not made."

I am not seeing this file ifd/databases/fathmm.py in the repository. 

Also just an FYI the Oncokb links are dead.

Thanks,
Michael

**Comment by mkinnaman** [comment]
Nevermind I see its in "predictors' - once everything is installed and set up  - what is the command to run on an input file?

**Comment by johannesreiter** [comment]
Thank you for identifying these bugs. I have now integrated the OncoKB changes and there are some basic options now available to run LiFD through the command line.
